services:
  frontend:
    build:
      context: ./frontend

    container_name: leanlytics-frontend

    ports:
      - "127.0.0.1:8080:80"

    restart: unless-stopped
    
  postgres:
    image: postgres:18

    container_name: leanlytics-postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: leanlytics
      POSTGRES_USER: leanlytics
      POSTGRES_PASSWORD: ${LOCAL_POSTGRES_PASSWORD}

    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: