# Generated by Django 6.0.6 on 2026-06-24 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='height',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='neck',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='waist',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='weight',
            field=models.FloatField(),
        ),
    ]
