# Generated by Django 6.0.6 on 2026-06-24 04:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0003_alter_measurement_height_alter_measurement_neck_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='measurement',
            index=models.Index(fields=['user', 'date'], name='measurement_user_id_633dab_idx'),
        ),
    ]
